# CountdownSigns By Relicum DO NOT CHANGE THESE AT THE MOMENT
sign:
  lines:
  - '&9&lTime Left'
  - '&a&l6D:16H:24M'
  - '&b&l&oTime Till'
  - '&4&lEXPLOSION'
# Settings section
  settings:
    identifier: '[CDS]'
    update-period: 20
    time-left: 600
    pause: true
    explosion: true
    use-sound: true
    use-effect: true
    debug: false
    auto-protect: true
