name: CountDownSigns
main: org.codemine.countdownsigns.CDS
author: Relicum
version: ${project.version}
description: CountDown Signs that destory the block below.

commands:
    cds:
        description: this is the main sub
        usage: /<command> [main]
        permission: countdown.sign
    cds remove:
        description: Any prefix command that all commands run under
        usage: /<command> sign|chickens|help
        aliases: [cdsr]
        permission: countdown.sign.remove
    cds toggle:
        description: Used to toogle the count down on and off
        usage: /<command> Used to toogle the count down on or off
        aliases: [cdsp]
        permission: countdown.sign.toggle
    cds status:
        description: Used to check the status of the countdown
        usage: /<command> Used to check the status of the command
        aliases: [cdss]
        permission: countdown.sign.status
    cds help:
        description: Various help guides, You can use Tab to see more options
        usage: /<command> [arg]
        aliases: [cdsh]
        permission: countdown.sign.help
    cds tp:
        description: Quick access back to the sign local using Teleport
        usage: /<command> tp
        aliases: [cdstp]
        permission: countdown.sign.tp
    cds set:
        description: Used to set settings related directly to this plugin
        usage: /<command> protection|enabeled|effect|help
        aliases: [cdsset]
        permission: countdown.sign.set


permissions:
    countdown.sign.*:
        description: Gives you all permissions
        children:
            countdown.sign.place: true
            countdown.sign.toggle: true
            countdown.sign.status: true
            countdown.sign.help: true
            countdown.sign.remove: true
            countdown.sign.tp: true
            countdown.sign.set: true
    countdown.sign.place:
        description: Allows the player to place Countdown Signs
        default: op
    countdown.sign.toggle:
        description: Allows you to toggle the countdown on and off
        default: op
    countdown.sign.status:
        description: Used to check the status of countdown
        default: op
    countdown.sign.help:
        description: View help guides
        default: op
    countdown.sign.remove:
        description: Remove the sign and all its configs
        default: op
    countdown.sign.tp:
        description: Allows admin to tp direct to the sign if there is any issues
        default: op
    countdown.sign.set:
         description: Oermission required to changing any of the plugins settings, while in game.
         default: op

